version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: glaz-finance-postgres
    environment:
      POSTGRES_DB: glaz_finance
      POSTGRES_USER: glaz_user
      POSTGRES_PASSWORD: glaz_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - glaz-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: glaz-finance-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - glaz-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: glaz-finance-backend
    environment:
      NODE_ENV: production
      PORT: 3002
      DATABASE_URL: postgresql://glaz_user:glaz_password_2024@postgres:5432/glaz_finance
      REDIS_URL: redis://redis:6379
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - glaz-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: glaz-finance-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3002
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - glaz-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: glaz-finance-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - glaz-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  glaz-network:
    driver: bridge
