name: Check Application Status

on:
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Application Status
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Checking application status..."
          pm2 list
          netstat -an | findstr :3002
          netstat -an | findstr :3001
