name: Check Scripts

on:
  workflow_dispatch:

jobs:
  check-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Scripts on Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Checking scripts directory..."
          dir C:\glaz-finance-app\scripts\
