name: Deploy Glaz Finance App v2.0

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Windows Server (v2.0)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "=== DEPLOYING GLAZ FINANCE APP v2.0 ==="
          
          echo "1. Setting environment variables..."
          set NODE_SKIP_PLATFORM_CHECK=1
          
          echo "2. Navigating to application directory..."
          cd C:\glaz-finance-app
          
          echo "3. Stopping existing processes..."
          taskkill /F /IM node.exe 2>nul || echo "No Node.js processes to stop"
          pm2 stop all 2>nul || echo "No PM2 processes to stop"
          
          echo "4. Pulling latest changes from GitHub..."
          git pull origin main
          
          echo "5. Installing dependencies..."
          npm install express cors --save
          
          echo "6. Starting Glaz Finance App v2.0 with PM2..."
          pm2 start glaz-finance-app-v2.js --name "glaz-finance-v2"
          pm2 save
          
          echo "7. Waiting for application to start..."
          timeout /t 5 /nobreak >nul
          
          echo "8. Checking PM2 status..."
          pm2 list
          
          echo "9. Checking if application is running..."
          netstat -an | findstr :3000
          
          echo "10. Testing local connection..."
          powershell -Command "try { Invoke-WebRequest -Uri 'http://localhost:3000' -TimeoutSec 5 | Out-Null; Write-Host '✅ Application is running!' } catch { Write-Host '❌ Application failed to start' }"
          
          echo "=== DEPLOYMENT COMPLETE ==="
          echo "Application should be available at: http://195.133.47.134:3000"
          echo "Features: HTML Interface + CRUD Operations"
