name: Deploy Main Application

on:
  workflow_dispatch:

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy Main Application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Setting environment variables..."
          set NODE_SKIP_PLATFORM_CHECK=1
          
          echo "Navigating to application directory..."
          cd C:\glaz-finance-app
          
          echo "Stopping existing PM2 processes..."
          pm2 stop all
          
          echo "Adding firewall rules..."
          netsh advfirewall firewall add rule name="Glaz Finance Frontend" dir=in action=allow protocol=TCP localport=3001
          netsh advfirewall firewall add rule name="Glaz Finance Backend" dir=in action=allow protocol=TCP localport=3002
          
          echo "Installing dependencies..."
          npm install
          npm install -g typescript
          
          echo "Installing backend dependencies..."
          cd backend
          npm install
          cd ..
          
          echo "Installing frontend dependencies..."
          cd frontend
          npm install --legacy-peer-deps
          cd ..
          
          echo "Creating PM2 configuration..."
          echo module.exports = { > ecosystem.config.js
          echo   apps : [{ >> ecosystem.config.js
          echo     name: 'glaz-finance-backend', >> ecosystem.config.js
          echo     script: './backend/index.js', >> ecosystem.config.js
          echo     instances: 1, >> ecosystem.config.js
          echo     autorestart: true, >> ecosystem.config.js
          echo     watch: false, >> ecosystem.config.js
          echo     max_memory_restart: '1G', >> ecosystem.config.js
          echo     env: { >> ecosystem.config.js
          echo       NODE_ENV: 'production', >> ecosystem.config.js
          echo       PORT: 3002, >> ecosystem.config.js
          echo       NODE_SKIP_PLATFORM_CHECK: '1' >> ecosystem.config.js
          echo     } >> ecosystem.config.js
          echo   }] >> ecosystem.config.js
          echo }; >> ecosystem.config.js
          
          echo "Starting PM2 processes..."
          pm2 start ecosystem.config.js
          pm2 save
          
          echo "Checking PM2 status..."
          pm2 list
          
          echo "Checking ports..."
          netstat -an | findstr :3002
          
          echo "Deployment completed! Application should be available at: http://195.133.47.134:3002"
