name: Deploy to Windows Server 2012 R2 (PM2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          Write-Host "Setting environment variables..." -ForegroundColor Green
          $env:NODE_SKIP_PLATFORM_CHECK = "1"
          
          Write-Host "Navigating to application directory..." -ForegroundColor Green
          cd C:\glaz-finance-app
          
          Write-Host "Stopping existing PM2 processes..." -ForegroundColor Yellow
          pm2 stop all
          
          Write-Host "Pulling latest changes..." -ForegroundColor Green
          git pull origin main
          
          Write-Host "Installing dependencies..." -ForegroundColor Green
          npm install
          
          Write-Host "Installing TypeScript globally..." -ForegroundColor Green
          npm install -g typescript
          
          Write-Host "Installing backend dependencies..." -ForegroundColor Green
          cd backend
          npm install
          cd ..
          
          Write-Host "Installing frontend dependencies..." -ForegroundColor Green
          cd frontend
          npm install --legacy-peer-deps
          cd ..
          
          Write-Host "Checking if backend JavaScript file exists..." -ForegroundColor Green
          if (!(Test-Path "backend\dist\index.js")) {
            Write-Host "Creating JavaScript backend file..." -ForegroundColor Yellow
            @"
          const express = require('express');
          const cors = require('cors');
          
          const app = express();
          const PORT = process.env.PORT || 3002;
          
          // Middleware
          app.use(cors());
          app.use(express.json());
          
          // Routes
          app.get('/', (req, res) => {
            res.json({ 
              message: 'Glaz Finance App Backend is running!',
              timestamp: new Date().toISOString(),
              port: PORT
            });
          });
          
          app.get('/health', (req, res) => {
            res.json({ 
              status: 'OK',
              uptime: process.uptime(),
              timestamp: new Date().toISOString()
            });
          });
          
          // Start server
          app.listen(PORT, () => {
            console.log(`🚀 Glaz Finance Backend is running on port ${PORT}`);
            console.log(`📊 Health check: http://localhost:${PORT}/health`);
          });
          "@ | Out-File -FilePath "backend\index.js" -Encoding UTF8
          }
          
          Write-Host "Creating PM2 configuration..." -ForegroundColor Green
          @"
          module.exports = {
            apps : [{
              name: 'glaz-finance-backend',
              script: './backend/index.js',
              instances: 1,
              autorestart: true,
              watch: false,
              max_memory_restart: '1G',
              env: {
                NODE_ENV: 'production',
                PORT: 3002,
                DATABASE_URL: 'sqlite://C:/glaz-finance-app/database/glaz_finance.db',
                REDIS_URL: 'redis://localhost:6379',
                NODE_SKIP_PLATFORM_CHECK: '1'
              }
            }, {
              name: 'glaz-finance-frontend',
              script: 'npm',
              args: 'start',
              cwd: './frontend',
              instances: 1,
              autorestart: true,
              watch: false,
              max_memory_restart: '1G',
              env: {
                NODE_ENV: 'production',
                PORT: 3001,
                REACT_APP_API_URL: 'http://localhost:3002',
                NODE_SKIP_PLATFORM_CHECK: '1'
              }
            }]
          };
          "@ | Out-File -FilePath "ecosystem-js.config.js" -Encoding UTF8
          
          Write-Host "Starting PM2 processes..." -ForegroundColor Green
          pm2 start ecosystem-js.config.js
          pm2 save
          
          Write-Host "Showing PM2 status..." -ForegroundColor Green
          pm2 list
          
          Write-Host "Checking port status..." -ForegroundColor Green
          netstat -an | findstr :3001
          netstat -an | findstr :3002
          
          Write-Host "Deployment completed! Application should be available at: http://195.133.47.134:3001" -ForegroundColor Green
