name: Deploy Currency Support v2.1

on:
  push:
    branches: [ main ]
    paths: 
      - 'glaz-finance-app-v2.js'
      - 'currency-service.js'
      - 'public/index.html'
      - 'package-simple.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy Currency Support v2.1 to Windows Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        timeout: 60s
        command_timeout: 30s
        debug: true
        script: |
          echo "=== Deploying Currency Support v2.1 ==="
          echo "Timestamp: $(Get-Date)"
          echo "Working directory: $(Get-Location)"
          
          # Navigate to project directory
          cd C:\glaz-finance-app
          echo "Changed to: $(Get-Location)"
          
          # Stop existing processes
          echo "Stopping existing processes..."
          pm2 stop all
          pm2 delete all
          
          # Pull latest changes
          echo "Pulling latest changes from GitHub..."
          git stash
          git clean -fd
          git fetch origin
          git reset --hard origin/main
          
          # Install dependencies
          echo "Installing dependencies..."
          npm install --production --package-lock=false
          
          # Start application with PM2
          echo "Starting application with PM2..."
          pm2 start glaz-finance-app-v2.js --name "glaz-finance-currency"
          
          # Save PM2 configuration
          pm2 save
          
          # Show status
          echo "=== Application Status ==="
          pm2 list
          pm2 logs --lines 10
          
          # Test endpoints
          echo "=== Testing Currency Endpoints ==="
          echo "Testing health endpoint..."
          Invoke-WebRequest -Uri "http://localhost:3000/health" -UseBasicParsing | Select-Object StatusCode, Content
          
          echo "Testing currencies endpoint..."
          Invoke-WebRequest -Uri "http://localhost:3000/api/currencies" -UseBasicParsing | Select-Object StatusCode
          
          echo "Testing conversion endpoint..."
          Invoke-WebRequest -Uri "http://localhost:3000/api/currencies/convert?amount=100&from=USD&to=RUB" -UseBasicParsing | Select-Object StatusCode
          
          echo "Testing total balance endpoint..."
          Invoke-WebRequest -Uri "http://localhost:3000/api/accounts/total?currency=USD" -UseBasicParsing | Select-Object StatusCode
          
          echo "=== Deployment Complete ==="
          echo "Currency Support v2.1 deployed successfully!"
          echo "External URL: http://195.133.47.134:3000"
