name: Emergency Fix

on:
  workflow_dispatch:

jobs:
  emergency:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Emergency Status Check
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "=== EMERGENCY STATUS CHECK ==="
          
          echo "1. Setting environment variables..."
          set NODE_SKIP_PLATFORM_CHECK=1
          
          echo "2. Navigating to application directory..."
          cd C:\glaz-finance-app
          
          echo "3. Running emergency check script..."
          powershell -ExecutionPolicy Bypass -File scripts\emergency-check.ps1
          
          echo "=== EMERGENCY CHECK COMPLETE ==="
