name: Fix Windows Firewall

on:
  workflow_dispatch:

jobs:
  fix-firewall:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure Windows Firewall
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Configuring Windows Firewall for application ports..."
          
          echo "Adding firewall rule for port 3001 (Frontend)..."
          netsh advfirewall firewall add rule name="Glaz Finance Frontend" dir=in action=allow protocol=TCP localport=3001
          
          echo "Adding firewall rule for port 3002 (Backend)..."
          netsh advfirewall firewall add rule name="Glaz Finance Backend" dir=in action=allow protocol=TCP localport=3002
          
          echo "Checking firewall rules..."
          netsh advfirewall firewall show rule name="Glaz Finance Frontend"
          netsh advfirewall firewall show rule name="Glaz Finance Backend"
          
          echo "Testing external access after firewall fix..."
          curl -s http://localhost:3002/health || echo "Backend still not accessible"
          curl -s http://localhost:3001 || echo "Frontend still not accessible"
          
          echo "Firewall configuration complete!"
