name: Quick Restore Port 3000

on:
  workflow_dispatch:

jobs:
  quick-restore:
    runs-on: ubuntu-latest
    
    steps:
    - name: Quick Restore Port 3000
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "=== QUICK RESTORE PORT 3000 ==="
          
          echo "1. Stopping all PM2 processes..."
          pm2 stop all
          pm2 delete all
          
          echo "2. Adding firewall rule for port 3000..."
          netsh advfirewall firewall add rule name="Port 3000 App" dir=in action=allow protocol=TCP localport=3000
          
          echo "3. Creating simple server for port 3000..."
          cd C:\glaz-finance-app
          @"
          const express = require('express');
          const app = express();
          const PORT = 3000;
          
          app.get('/', (req, res) => {
            res.json({ 
              message: 'Port 3000 Application Restored!',
              timestamp: new Date().toISOString(),
              port: PORT
            });
          });
          
          app.get('/health', (req, res) => {
            res.json({ 
              status: 'OK',
              timestamp: new Date().toISOString(),
              port: PORT
            });
          });
          
          app.listen(PORT, '0.0.0.0', () => {
            console.log(`Port 3000 server running on ${PORT}`);
          });
          "@ > port3000-server.js
          
          echo "4. Starting port 3000 server with PM2..."
          pm2 start port3000-server.js --name "port3000-app"
          pm2 save
          
          echo "5. Checking PM2 status..."
          pm2 list
          
          echo "6. Testing port 3000..."
          curl -s http://localhost:3000 || echo "Port 3000 test failed"
          
          echo "7. Checking port status..."
          netstat -an | findstr :3000
          
          echo "=== PORT 3000 RESTORED ==="
