name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 195.133.47.134
        username: github-deploy
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          echo "SSH connection test successful!"
          echo "Current time: $(Get-Date)"
          echo "Server: $(hostname)"
