name: Test Node.js

on:
  workflow_dispatch:

jobs:
  test-node:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Node.js
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "Testing Node.js..."
          node --version
          npm --version
